//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.ServicesProxies.BddViolationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficViolationRequestData", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    [System.SerializableAttribute()]
    public partial class TrafficViolationRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberSRTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalName {
            get {
                return this.LegalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNameField, value) != true)) {
                    this.LegalNameField = value;
                    this.RaisePropertyChanged("LegalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberSRTS {
            get {
                return this.NumberSRTSField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberSRTSField, value) != true)) {
                    this.NumberSRTSField = value;
                    this.RaisePropertyChanged("NumberSRTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secondname {
            get {
                return this.SecondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondnameField, value) != true)) {
                    this.SecondnameField = value;
                    this.RaisePropertyChanged("Secondname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportNumber {
            get {
                return this.TransportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportNumberField, value) != true)) {
                    this.TransportNumberField = value;
                    this.RaisePropertyChanged("TransportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficViolationServiceResult", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    [System.SerializableAttribute()]
    public partial class TrafficViolationServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DT.PCP.ServicesProxies.BddViolationService.ResultCodeEnum ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData[] TrafficViolationDataListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DT.PCP.ServicesProxies.BddViolationService.ResultCodeEnum ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData[] TrafficViolationDataList {
            get {
                return this.TrafficViolationDataListField;
            }
            set {
                if ((object.ReferenceEquals(this.TrafficViolationDataListField, value) != true)) {
                    this.TrafficViolationDataListField = value;
                    this.RaisePropertyChanged("TrafficViolationDataList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCodeEnum", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    public enum ResultCodeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonAuthentificationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConnectionError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestParametersError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InformationNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrescriptionPaid = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficViolationData", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    [System.SerializableAttribute()]
    public partial class TrafficViolationData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FineCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FixationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLegalEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRepeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberSRTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DT.PCP.ServicesProxies.BddViolationService.ViolationStatusEnum ViolationStatusEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolationStatusKzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolationTypeKzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolationTypeShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolatorFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolatorFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolatorLastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViolatorSecondnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FineCost {
            get {
                return this.FineCostField;
            }
            set {
                if ((this.FineCostField.Equals(value) != true)) {
                    this.FineCostField = value;
                    this.RaisePropertyChanged("FineCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FixationDateTime {
            get {
                return this.FixationDateTimeField;
            }
            set {
                if ((this.FixationDateTimeField.Equals(value) != true)) {
                    this.FixationDateTimeField = value;
                    this.RaisePropertyChanged("FixationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLegalEntity {
            get {
                return this.IsLegalEntityField;
            }
            set {
                if ((this.IsLegalEntityField.Equals(value) != true)) {
                    this.IsLegalEntityField = value;
                    this.RaisePropertyChanged("IsLegalEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRepeat {
            get {
                return this.IsRepeatField;
            }
            set {
                if ((this.IsRepeatField.Equals(value) != true)) {
                    this.IsRepeatField = value;
                    this.RaisePropertyChanged("IsRepeat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkField, value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberSRTS {
            get {
                return this.NumberSRTSField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberSRTSField, value) != true)) {
                    this.NumberSRTSField = value;
                    this.RaisePropertyChanged("NumberSRTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostAddress {
            get {
                return this.PostAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostAddressField, value) != true)) {
                    this.PostAddressField = value;
                    this.RaisePropertyChanged("PostAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportNumber {
            get {
                return this.TransportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportNumberField, value) != true)) {
                    this.TransportNumberField = value;
                    this.RaisePropertyChanged("TransportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolationStatus {
            get {
                return this.ViolationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolationStatusField, value) != true)) {
                    this.ViolationStatusField = value;
                    this.RaisePropertyChanged("ViolationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DT.PCP.ServicesProxies.BddViolationService.ViolationStatusEnum ViolationStatusEnum {
            get {
                return this.ViolationStatusEnumField;
            }
            set {
                if ((this.ViolationStatusEnumField.Equals(value) != true)) {
                    this.ViolationStatusEnumField = value;
                    this.RaisePropertyChanged("ViolationStatusEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolationStatusKz {
            get {
                return this.ViolationStatusKzField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolationStatusKzField, value) != true)) {
                    this.ViolationStatusKzField = value;
                    this.RaisePropertyChanged("ViolationStatusKz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolationType {
            get {
                return this.ViolationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolationTypeField, value) != true)) {
                    this.ViolationTypeField = value;
                    this.RaisePropertyChanged("ViolationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolationTypeKz {
            get {
                return this.ViolationTypeKzField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolationTypeKzField, value) != true)) {
                    this.ViolationTypeKzField = value;
                    this.RaisePropertyChanged("ViolationTypeKz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolationTypeShort {
            get {
                return this.ViolationTypeShortField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolationTypeShortField, value) != true)) {
                    this.ViolationTypeShortField = value;
                    this.RaisePropertyChanged("ViolationTypeShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolatorFirstname {
            get {
                return this.ViolatorFirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolatorFirstnameField, value) != true)) {
                    this.ViolatorFirstnameField = value;
                    this.RaisePropertyChanged("ViolatorFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolatorFullName {
            get {
                return this.ViolatorFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolatorFullNameField, value) != true)) {
                    this.ViolatorFullNameField = value;
                    this.RaisePropertyChanged("ViolatorFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolatorLastname {
            get {
                return this.ViolatorLastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolatorLastnameField, value) != true)) {
                    this.ViolatorLastnameField = value;
                    this.RaisePropertyChanged("ViolatorLastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViolatorSecondname {
            get {
                return this.ViolatorSecondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ViolatorSecondnameField, value) != true)) {
                    this.ViolatorSecondnameField = value;
                    this.RaisePropertyChanged("ViolatorSecondname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViolationStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    public enum ViolationStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderCreated = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderPrinted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifySended = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayChecked = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportOwnerData", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.RTM.InfoCenter.Services")]
    [System.SerializableAttribute()]
    public partial class TransportOwnerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLegalEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberSRTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransportYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLegalEntity {
            get {
                return this.IsLegalEntityField;
            }
            set {
                if ((this.IsLegalEntityField.Equals(value) != true)) {
                    this.IsLegalEntityField = value;
                    this.RaisePropertyChanged("IsLegalEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkField, value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberSRTS {
            get {
                return this.NumberSRTSField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberSRTSField, value) != true)) {
                    this.NumberSRTSField = value;
                    this.RaisePropertyChanged("NumberSRTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerFirstName {
            get {
                return this.OwnerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerFirstNameField, value) != true)) {
                    this.OwnerFirstNameField = value;
                    this.RaisePropertyChanged("OwnerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerFullName {
            get {
                return this.OwnerFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerFullNameField, value) != true)) {
                    this.OwnerFullNameField = value;
                    this.RaisePropertyChanged("OwnerFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerLastName {
            get {
                return this.OwnerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerLastNameField, value) != true)) {
                    this.OwnerLastNameField = value;
                    this.RaisePropertyChanged("OwnerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerSecondName {
            get {
                return this.OwnerSecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSecondNameField, value) != true)) {
                    this.OwnerSecondNameField = value;
                    this.RaisePropertyChanged("OwnerSecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterAddress {
            get {
                return this.RegisterAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterAddressField, value) != true)) {
                    this.RegisterAddressField = value;
                    this.RaisePropertyChanged("RegisterAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportNumber {
            get {
                return this.TransportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportNumberField, value) != true)) {
                    this.TransportNumberField = value;
                    this.RaisePropertyChanged("TransportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransportYear {
            get {
                return this.TransportYearField;
            }
            set {
                if ((this.TransportYearField.Equals(value) != true)) {
                    this.TransportYearField = value;
                    this.RaisePropertyChanged("TransportYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BddViolationService.ITrafficViolationService")]
    public interface ITrafficViolationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolations", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsResponse")]
        DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult GetTrafficViolations(DT.PCP.ServicesProxies.BddViolationService.TrafficViolationRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolations", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsResponse")]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult> GetTrafficViolationsAsync(DT.PCP.ServicesProxies.BddViolationService.TrafficViolationRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsByName", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsByNameResponse")]
        DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult GetTrafficViolationsByName(string driverFullName, System.Nullable<System.DateTime> birthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsByName", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationsByNameResponse")]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult> GetTrafficViolationsByNameAsync(string driverFullName, System.Nullable<System.DateTime> birthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTransportOwner", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTransportOwnerResponse")]
        DT.PCP.ServicesProxies.BddViolationService.TransportOwnerData GetTransportOwner(string grnz, string srts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTransportOwner", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTransportOwnerResponse")]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TransportOwnerData> GetTransportOwnerAsync(string grnz, string srts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolation", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationResponse")]
        DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData GetTrafficViolation(string grnz, string orderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolation", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationResponse")]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData> GetTrafficViolationAsync(string grnz, string orderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolationImage", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationImageResponse")]
        System.IO.Stream GetTrafficViolationImage(string orderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationService/GetTrafficViolationImage", ReplyAction="http://tempuri.org/ITrafficViolationService/GetTrafficViolationImageResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetTrafficViolationImageAsync(string orderNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficViolationServiceChannel : DT.PCP.ServicesProxies.BddViolationService.ITrafficViolationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficViolationServiceClient : System.ServiceModel.ClientBase<DT.PCP.ServicesProxies.BddViolationService.ITrafficViolationService>, DT.PCP.ServicesProxies.BddViolationService.ITrafficViolationService {
        
        public TrafficViolationServiceClient() {
        }
        
        public TrafficViolationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrafficViolationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficViolationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficViolationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult GetTrafficViolations(DT.PCP.ServicesProxies.BddViolationService.TrafficViolationRequestData requestData) {
            return base.Channel.GetTrafficViolations(requestData);
        }
        
        public System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult> GetTrafficViolationsAsync(DT.PCP.ServicesProxies.BddViolationService.TrafficViolationRequestData requestData) {
            return base.Channel.GetTrafficViolationsAsync(requestData);
        }
        
        public DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult GetTrafficViolationsByName(string driverFullName, System.Nullable<System.DateTime> birthDate) {
            return base.Channel.GetTrafficViolationsByName(driverFullName, birthDate);
        }
        
        public System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationServiceResult> GetTrafficViolationsByNameAsync(string driverFullName, System.Nullable<System.DateTime> birthDate) {
            return base.Channel.GetTrafficViolationsByNameAsync(driverFullName, birthDate);
        }
        
        public DT.PCP.ServicesProxies.BddViolationService.TransportOwnerData GetTransportOwner(string grnz, string srts) {
            return base.Channel.GetTransportOwner(grnz, srts);
        }
        
        public System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TransportOwnerData> GetTransportOwnerAsync(string grnz, string srts) {
            return base.Channel.GetTransportOwnerAsync(grnz, srts);
        }
        
        public DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData GetTrafficViolation(string grnz, string orderNumber) {
            return base.Channel.GetTrafficViolation(grnz, orderNumber);
        }
        
        public System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddViolationService.TrafficViolationData> GetTrafficViolationAsync(string grnz, string orderNumber) {
            return base.Channel.GetTrafficViolationAsync(grnz, orderNumber);
        }
        
        public System.IO.Stream GetTrafficViolationImage(string orderNumber) {
            return base.Channel.GetTrafficViolationImage(orderNumber);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetTrafficViolationImageAsync(string orderNumber) {
            return base.Channel.GetTrafficViolationImageAsync(orderNumber);
        }
    }
}
