//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Cabinet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CabinetViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CabinetViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Cabinet.CabinetViewsStrings", typeof(CabinetViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как изменить свои данные?.
        /// </summary>
        public static string ButtonHelpChangeUserInfo {
            get {
                return ResourceManager.GetString("ButtonHelpChangeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что означает кнопка «Проверить»?.
        /// </summary>
        public static string ButtonHelpLoadFromServer {
            get {
                return ResourceManager.GetString("ButtonHelpLoadFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что такое уведомления и как подписаться?.
        /// </summary>
        public static string ButtonHelpWhatIsNotification {
            get {
                return ResourceManager.GetString("ButtonHelpWhatIsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить.
        /// </summary>
        public static string ButtonLoadFromServer {
            get {
                return ResourceManager.GetString("ButtonLoadFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string ButtonNotification {
            get {
                return ResourceManager.GetString("ButtonNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ButtonNotificationSave {
            get {
                return ResourceManager.GetString("ButtonNotificationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ButtonRedirectToHome {
            get {
                return ResourceManager.GetString("ButtonRedirectToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ButtonSaveEditInfo {
            get {
                return ResourceManager.GetString("ButtonSaveEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписаться.
        /// </summary>
        public static string ButtonSubscribe {
            get {
                return ResourceManager.GetString("ButtonSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться.
        /// </summary>
        public static string ButtonUnsubscribe {
            get {
                return ResourceManager.GetString("ButtonUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string ButtonViolationListClear {
            get {
                return ResourceManager.GetString("ButtonViolationListClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string ButtonViolationListPay {
            get {
                return ResourceManager.GetString("ButtonViolationListPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string ButtonViolationListSearch {
            get {
                return ResourceManager.GetString("ButtonViolationListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        public static string CabinetTitle {
            get {
                return ResourceManager.GetString("CabinetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для данного действия необходимо войти на сайт. Перейдите на главную страницу и войдите на сайт.
        /// </summary>
        public static string ContentAuthRequiredDescription {
            get {
                return ResourceManager.GetString("ContentAuthRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по адресу.
        /// </summary>
        public static string ContentDetailByAddress {
            get {
                return ResourceManager.GetString("ContentDetailByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль №.
        /// </summary>
        public static string ContentDetailCarNumber {
            get {
                return ResourceManager.GetString("ContentDetailCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штраф.
        /// </summary>
        public static string ContentDetailViolationCost {
            get {
                return ResourceManager.GetString("ContentDetailViolationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нарушитель.
        /// </summary>
        public static string ContentDetailViolator {
            get {
                return ResourceManager.GetString("ContentDetailViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрирован по адресу.
        /// </summary>
        public static string ContentInfoPartialAddressRegistration {
            get {
                return ResourceManager.GetString("ContentInfoPartialAddressRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль.
        /// </summary>
        public static string ContentInfoPartialCarNumber {
            get {
                return ResourceManager.GetString("ContentInfoPartialCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поиска введите тип нарушения, адрес нарушения или дату.
        /// </summary>
        public static string ContentViolationListSearchPlaceholder {
            get {
                return ResourceManager.GetString("ContentViolationListSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных.
        /// </summary>
        public static string FormEditInfo {
            get {
                return ResourceManager.GetString("FormEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать данные.
        /// </summary>
        public static string MessageEditInfo {
            get {
                return ResourceManager.GetString("MessageEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните email.
        /// </summary>
        public static string MessageFillEmail {
            get {
                return ResourceManager.GetString("MessageFillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните телефон.
        /// </summary>
        public static string MessageFillPhone {
            get {
                return ResourceManager.GetString("MessageFillPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросить данные с сервера.
        /// </summary>
        public static string MessageLoadInfoFromService {
            get {
                return ResourceManager.GetString("MessageLoadInfoFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не найдены.
        /// </summary>
        public static string ModalDataNotFoundBody {
            get {
                return ResourceManager.GetString("ModalDataNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных с сервера.
        /// </summary>
        public static string ModalDataNotFoundHeader {
            get {
                return ResourceManager.GetString("ModalDataNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string ModalDetailButtonPay {
            get {
                return ResourceManager.GetString("ModalDetailButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нарушение.
        /// </summary>
        public static string ModalDetailsHeader {
            get {
                return ResourceManager.GetString("ModalDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string ModalDetailsHeaderAdj {
            get {
                return ResourceManager.GetString("ModalDetailsHeaderAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инстуркция редактирования данных.
        /// </summary>
        public static string ModalEditInstructionHeader {
            get {
                return ResourceManager.GetString("ModalEditInstructionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка доступа.
        /// </summary>
        public static string ModalHeaderAuthRequired {
            get {
                return ResourceManager.GetString("ModalHeaderAuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение о подписке на уведомления.
        /// </summary>
        public static string ModalHeaderConfirmationNotification {
            get {
                return ResourceManager.GetString("ModalHeaderConfirmationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о нарушениях.
        /// </summary>
        public static string ModalHeaderNotification {
            get {
                return ResourceManager.GetString("ModalHeaderNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписаться.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие сведения.
        /// </summary>
        public static string TabGeneralInfo {
            get {
                return ResourceManager.GetString("TabGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        public static string TabNewViolation {
            get {
                return ResourceManager.GetString("TabNewViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплаченные.
        /// </summary>
        public static string TabPayedViolation {
            get {
                return ResourceManager.GetString("TabPayedViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список оплаченных нарушений.
        /// </summary>
        public static string TabViolationList {
            get {
                return ResourceManager.GetString("TabViolationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string TitleProfile {
            get {
                return ResourceManager.GetString("TitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список нарушений.
        /// </summary>
        public static string TitleViolationList {
            get {
                return ResourceManager.GetString("TitleViolationList", resourceCulture);
            }
        }
    }
}
