//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Pay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PayViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Pay.PayViewsStrings", typeof(PayViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string ButtonConfirmInfo {
            get {
                return ResourceManager.GetString("ButtonConfirmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковские карты.
        /// </summary>
        public static string ButtonCreditCard {
            get {
                return ResourceManager.GetString("ButtonCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминалы оплаты.
        /// </summary>
        public static string ButtonTerminal {
            get {
                return ResourceManager.GetString("ButtonTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиссия.
        /// </summary>
        public static string ContentCommission {
            get {
                return ResourceManager.GetString("ContentCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма штрафа.
        /// </summary>
        public static string ContentCost {
            get {
                return ResourceManager.GetString("ContentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте заполнение полей.
        /// </summary>
        public static string ContentHelpChapterCheck {
            get {
                return ResourceManager.GetString("ContentHelpChapterCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесите необходимую сумму.
        /// </summary>
        public static string ContentHelpChapterEnterMoney {
            get {
                return ResourceManager.GetString("ContentHelpChapterEnterMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер предписания.
        /// </summary>
        public static string ContentHelpChapterEnterOrderNumber {
            get {
                return ResourceManager.GetString("ContentHelpChapterEnterOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел &quot;Другие услуги&quot;.
        /// </summary>
        public static string ContentHelpChapterOtherService {
            get {
                return ResourceManager.GetString("ContentHelpChapterOtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите кнопку оплатить.
        /// </summary>
        public static string ContentHelpChapterPayButton {
            get {
                return ResourceManager.GetString("ContentHelpChapterPayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел &quot;Оплата услуг&quot;.
        /// </summary>
        public static string ContentHelpChapterPayService {
            get {
                return ResourceManager.GetString("ContentHelpChapterPayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел &quot;Оплата нарушений&quot;.
        /// </summary>
        public static string ContentHelpChapterViolationPay {
            get {
                return ResourceManager.GetString("ContentHelpChapterViolationPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер предписания.
        /// </summary>
        public static string ContentOrderNumber {
            get {
                return ResourceManager.GetString("ContentOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете оплатить &lt;span class=&quot;text-info&quot;&gt;&lt;strong&gt;БАНКОВСКИМИ КАРТАМИ&lt;/strong&gt;&lt;/span&gt; (Visa, MasterCard, Cirrus Maestro) через платежную систему E-Pay.
        /// </summary>
        public static string ContentPayWayCardPayDescription {
            get {
                return ResourceManager.GetString("ContentPayWayCardPayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете оплатить нарушение при помощи &lt;span class=&quot;text-info&quot;&gt;&lt;strong&gt;ПЛАТЕЖНЫХ ТЕРМИНАЛОВ&lt;/strong&gt;&lt;/span&gt;, которые находятся в большинстве магазинах и супермаркетах, торгово-развлекательных центрах и административных зданиях.
        /// </summary>
        public static string ContentPayWayTerminalPayDescription {
            get {
                return ResourceManager.GetString("ContentPayWayTerminalPayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong style=&quot;color: #5ca1e2;&quot;&gt;Внимание!&lt;/strong&gt; Терминал сдачи не выдает. Остаток средств после оплаты нарушения будет переведен на баланс мобильного телефона, указанного при оплате.
        /// </summary>
        public static string ContentTerminalPayInfoMoneyTransfer {
            get {
                return ResourceManager.GetString("ContentTerminalPayInfoMoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        public static string ContentTotal {
            get {
                return ResourceManager.GetString("ContentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение персональных данных.
        /// </summary>
        public static string HeaderUserConfirmation {
            get {
                return ResourceManager.GetString("HeaderUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение заказа.
        /// </summary>
        public static string TitleConfirmOrder {
            get {
                return ResourceManager.GetString("TitleConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способ оплаты.
        /// </summary>
        public static string TitlePayWay {
            get {
                return ResourceManager.GetString("TitlePayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата платежным терминалом.
        /// </summary>
        public static string TitleTerminalPayInfo {
            get {
                return ResourceManager.GetString("TitleTerminalPayInfo", resourceCulture);
            }
        }
    }
}
