//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Account.AccountViewsStrings", typeof(AccountViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ModalCloseButton {
            get {
                return ResourceManager.GetString("ModalCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось соединится с сервером.  Повторите попытку позже.
        /// </summary>
        public static string ModalServerNotRespondBody {
            get {
                return ResourceManager.GetString("ModalServerNotRespondBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка транспортного средства.
        /// </summary>
        public static string ModalServerNotRespondHeader {
            get {
                return ResourceManager.GetString("ModalServerNotRespondHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены некорректные данные о транспортном средстве.
        /// </summary>
        public static string ModalSrtsNotEqualBody {
            get {
                return ResourceManager.GetString("ModalSrtsNotEqualBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка транспортного средства.
        /// </summary>
        public static string ModalSrtsNotEqualHeader {
            get {
                return ResourceManager.GetString("ModalSrtsNotEqualHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенный номер техпаспорта незарегестрирован в ДВД.
        /// </summary>
        public static string ModalSrtsNotFoundBody {
            get {
                return ResourceManager.GetString("ModalSrtsNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка транспортного средства.
        /// </summary>
        public static string ModalSrtsNotFoundHeader {
            get {
                return ResourceManager.GetString("ModalSrtsNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспортное средство не найдено.
        /// </summary>
        public static string ModalTsNotFoundBody {
            get {
                return ResourceManager.GetString("ModalTsNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка транспортного средства.
        /// </summary>
        public static string ModalTsNotFoundHeader {
            get {
                return ResourceManager.GetString("ModalTsNotFoundHeader", resourceCulture);
            }
        }
    }
}
