//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Home.HomeViewsStrings", typeof(HomeViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как войти?.
        /// </summary>
        public static string ButtonHelpHowToLogin {
            get {
                return ResourceManager.GetString("ButtonHelpHowToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как оплатить?.
        /// </summary>
        public static string ButtonHelpHowToPay {
            get {
                return ResourceManager.GetString("ButtonHelpHowToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как подписаться?.
        /// </summary>
        public static string ButtonHelpHowToSubscribe {
            get {
                return ResourceManager.GetString("ButtonHelpHowToSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ButtonProfile {
            get {
                return ResourceManager.GetString("ButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск нарушений.
        /// </summary>
        public static string ButtonViolationPay {
            get {
                return ResourceManager.GetString("ButtonViolationPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковские карты.
        /// </summary>
        public static string ContentCardPay {
            get {
                return ResourceManager.GetString("ContentCardPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна оплата штрафов по нарушениям при помощи банковских платежных карт  Visa, MasterCard различных банков.
        /// </summary>
        public static string ContentCardPayDescription {
            get {
                return ResourceManager.GetString("ContentCardPayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string ContentNotification {
            get {
                return ResourceManager.GetString("ContentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете подписаться на email, sms-уведомление о выписанных штрафах, для получения данных о нарушениях.
        /// </summary>
        public static string ContentNotificationDescription {
            get {
                return ResourceManager.GetString("ContentNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИЛИ.
        /// </summary>
        public static string ContentOr {
            get {
                return ResourceManager.GetString("ContentOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт специально разработан  для доступного и удобного просмотра сведений о нарушениях владельцем транспортного средства, а также для он-лайн оплаты штрафов по ним удобным для Вас способом. Для того, чтобы просмотреть список нарушений, Вам достаточно ввести номер автомобиля и № техпаспорта, либо номер автомобиля и № предписания по нарушению, и нажать кнопку  &lt;strong style=&quot;color: #5ca1e2;&quot;&gt;&amp;laquo;Войти&amp;raquo;&lt;/strong&gt;.
        /// </summary>
        public static string ContentSiteDescription {
            get {
                return ResourceManager.GetString("ContentSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна возможность оплаты штрафов по нарушениям при помощи платежных терминалов.
        /// </summary>
        public static string ContentTerminalDescription {
            get {
                return ResourceManager.GetString("ContentTerminalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминалы оплаты.
        /// </summary>
        public static string ContentTerminalPay {
            get {
                return ResourceManager.GetString("ContentTerminalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string ContentWelcome {
            get {
                return ResourceManager.GetString("ContentWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на сайт оплаты штрафов.
        /// </summary>
        public static string ContentWelcomeTo {
            get {
                return ResourceManager.GetString("ContentWelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № автомобиля.
        /// </summary>
        public static string PlaceholderCarNumber {
            get {
                return ResourceManager.GetString("PlaceholderCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № техпаспорта.
        /// </summary>
        public static string PlaceholderCarPassportNumber {
            get {
                return ResourceManager.GetString("PlaceholderCarPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер предписания.
        /// </summary>
        public static string PlaceholderOrderNumber {
            get {
                return ResourceManager.GetString("PlaceholderOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить номер автомобиля.
        /// </summary>
        public static string ValidationCarNumber {
            get {
                return ResourceManager.GetString("ValidationCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить номер техпаспорта.
        /// </summary>
        public static string ValidationCarPassportNumber {
            get {
                return ResourceManager.GetString("ValidationCarPassportNumber", resourceCulture);
            }
        }
    }
}
