//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupportViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupportViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Support.SupportViewsStrings", typeof(SupportViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как изменить свои данные?.
        /// </summary>
        public static string LinkHelpChangeUserInfo {
            get {
                return ResourceManager.GetString("LinkHelpChangeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос - ответ.
        /// </summary>
        public static string LinkHelpFaq {
            get {
                return ResourceManager.GetString("LinkHelpFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как войти с вводом номер авто+номер техпаспорта?.
        /// </summary>
        public static string LinkHelpHoToLoginCarPassport {
            get {
                return ResourceManager.GetString("LinkHelpHoToLoginCarPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как войти с вводом номер авто+номер предписания?.
        /// </summary>
        public static string LinkHelpHoToLoginOrderNumber {
            get {
                return ResourceManager.GetString("LinkHelpHoToLoginOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как изменить данные подписки на уведомления?.
        /// </summary>
        public static string LinkHelpHowToChangeSubscribe {
            get {
                return ResourceManager.GetString("LinkHelpHowToChangeSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как войти?.
        /// </summary>
        public static string LinkHelpHowToLogin {
            get {
                return ResourceManager.GetString("LinkHelpHowToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как оплатить нарушения?.
        /// </summary>
        public static string LinkHelpHowToPay {
            get {
                return ResourceManager.GetString("LinkHelpHowToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как оплатить нарушения с помощью банковских карт?.
        /// </summary>
        public static string LinkHelpHowToPayByCard {
            get {
                return ResourceManager.GetString("LinkHelpHowToPayByCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как оплатить нарушения с помощью платежного терминала?.
        /// </summary>
        public static string LinkHelpHowToPayByTerminal {
            get {
                return ResourceManager.GetString("LinkHelpHowToPayByTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как подписаться на уведомления?.
        /// </summary>
        public static string LinkHelpHowToSubscribe {
            get {
                return ResourceManager.GetString("LinkHelpHowToSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как отписаться от уведомлений?.
        /// </summary>
        public static string LinkHelpHowToUnsubscribe {
            get {
                return ResourceManager.GetString("LinkHelpHowToUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как узнать, прошла ли проплата штрафа?.
        /// </summary>
        public static string LinkHelpIsPaySuccess {
            get {
                return ResourceManager.GetString("LinkHelpIsPaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как посмотреть данные об авто?.
        /// </summary>
        public static string LinkHelpProfile {
            get {
                return ResourceManager.GetString("LinkHelpProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как посмотреть данные о нарушениях?.
        /// </summary>
        public static string LinkHelpViolationList {
            get {
                return ResourceManager.GetString("LinkHelpViolationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка.
        /// </summary>
        public static string TitleSupport {
            get {
                return ResourceManager.GetString("TitleSupport", resourceCulture);
            }
        }
    }
}
