//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.ServicesProxies.BddPayRegisterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficViolationPayData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TrafficViolationPayData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string code_bankField;
        
        private DT.PCP.ServicesProxies.BddPayRegisterService.PayMethodAlias system_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string n_billing_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string u_reference_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string n_prescriField;
        
        private double pay_penaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rnn_iin_bin_payerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_payerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code_bank {
            get {
                return this.code_bankField;
            }
            set {
                if ((object.ReferenceEquals(this.code_bankField, value) != true)) {
                    this.code_bankField = value;
                    this.RaisePropertyChanged("code_bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.PayMethodAlias system_id {
            get {
                return this.system_idField;
            }
            set {
                if ((this.system_idField.Equals(value) != true)) {
                    this.system_idField = value;
                    this.RaisePropertyChanged("system_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string n_billing_doc {
            get {
                return this.n_billing_docField;
            }
            set {
                if ((object.ReferenceEquals(this.n_billing_docField, value) != true)) {
                    this.n_billing_docField = value;
                    this.RaisePropertyChanged("n_billing_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string u_reference_doc {
            get {
                return this.u_reference_docField;
            }
            set {
                if ((object.ReferenceEquals(this.u_reference_docField, value) != true)) {
                    this.u_reference_docField = value;
                    this.RaisePropertyChanged("u_reference_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string n_prescri {
            get {
                return this.n_prescriField;
            }
            set {
                if ((object.ReferenceEquals(this.n_prescriField, value) != true)) {
                    this.n_prescriField = value;
                    this.RaisePropertyChanged("n_prescri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double pay_penalty {
            get {
                return this.pay_penaltyField;
            }
            set {
                if ((this.pay_penaltyField.Equals(value) != true)) {
                    this.pay_penaltyField = value;
                    this.RaisePropertyChanged("pay_penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rnn_iin_bin_payer {
            get {
                return this.rnn_iin_bin_payerField;
            }
            set {
                if ((object.ReferenceEquals(this.rnn_iin_bin_payerField, value) != true)) {
                    this.rnn_iin_bin_payerField = value;
                    this.RaisePropertyChanged("rnn_iin_bin_payer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string name_payer {
            get {
                return this.name_payerField;
            }
            set {
                if ((object.ReferenceEquals(this.name_payerField, value) != true)) {
                    this.name_payerField = value;
                    this.RaisePropertyChanged("name_payer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CorrelationID {
            get {
                return this.CorrelationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIDField, value) != true)) {
                    this.CorrelationIDField = value;
                    this.RaisePropertyChanged("CorrelationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayMethodAlias", Namespace="http://tempuri.org/")]
    public enum PayMethodAlias : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACQUIRE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACQUIREByCardReader = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayOrder = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManualPay = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayRegister = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficViolationPayResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TrafficViolationPayResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        private DT.PCP.ServicesProxies.BddPayRegisterService.ResultCodeEnum ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.ResultCodeEnum ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodeBank {
            get {
                return this.CodeBankField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBankField, value) != true)) {
                    this.CodeBankField = value;
                    this.RaisePropertyChanged("CodeBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CorrelationID {
            get {
                return this.CorrelationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIDField, value) != true)) {
                    this.CorrelationIDField = value;
                    this.RaisePropertyChanged("CorrelationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCodeEnum", Namespace="http://tempuri.org/")]
    public enum ResultCodeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonAuthentificationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConnectionError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestParametersError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InformationNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrescriptionPaid = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BddPayRegisterService.ITrafficViolationPayRegister")]
    public interface ITrafficViolationPayRegister {
        
        // CODEGEN: Generating message contract since element name payData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationPayRegister/Register", ReplyAction="http://tempuri.org/ITrafficViolationPayRegister/RegisterResponse")]
        DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse Register(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficViolationPayRegister/Register", ReplyAction="http://tempuri.org/ITrafficViolationPayRegister/RegisterResponse")]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse> RegisterAsync(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayData payData;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayData payData) {
            this.payData = payData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayResult RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayResult RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficViolationPayRegisterChannel : DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficViolationPayRegisterClient : System.ServiceModel.ClientBase<DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister>, DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister {
        
        public TrafficViolationPayRegisterClient() {
        }
        
        public TrafficViolationPayRegisterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrafficViolationPayRegisterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficViolationPayRegisterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficViolationPayRegisterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister.Register(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayResult Register(DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayData payData) {
            DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest inValue = new DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest();
            inValue.Body = new DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequestBody();
            inValue.Body.payData = payData;
            DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse retVal = ((DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse> DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister.RegisterAsync(DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DT.PCP.ServicesProxies.BddPayRegisterService.RegisterResponse> RegisterAsync(DT.PCP.ServicesProxies.BddPayRegisterService.TrafficViolationPayData payData) {
            DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest inValue = new DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequest();
            inValue.Body = new DT.PCP.ServicesProxies.BddPayRegisterService.RegisterRequestBody();
            inValue.Body.payData = payData;
            return ((DT.PCP.ServicesProxies.BddPayRegisterService.ITrafficViolationPayRegister)(this)).RegisterAsync(inValue);
        }
    }
}
