//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpViewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpViewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Help.HelpViewsStrings", typeof(HelpViewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ButtonEnter {
            get {
                return ResourceManager.GetString("ButtonEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопка &lt;strong style=&quot;color: #5ca1e2;&quot;&gt;&amp;laquo;Проверить&amp;raquo;&lt;/strong&gt; позволяет заново загрузить информацию об автомобиле из системы регистрации нарушений. Вам откроется новое окно с новыми данными. В этом же окне Вы можете дополнить или изменить данные. После внесения данных необходимо нажать кнопку &lt;strong style=&quot;color: #5ca1e2;&quot;&gt;&amp;laquo;Сохранить&amp;raquo;&lt;/strong&gt;. Вся информация при этом будет перезаписана..
        /// </summary>
        public static string ContentCheckInfo {
            get {
                return ResourceManager.GetString("ContentCheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить.
        /// </summary>
        public static string ModalCheckInfoHeader {
            get {
                return ResourceManager.GetString("ModalCheckInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных.
        /// </summary>
        public static string ModalEditInfoHeader {
            get {
                return ResourceManager.GetString("ModalEditInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как войти?.
        /// </summary>
        public static string ModalLoginInfoHeader {
            get {
                return ResourceManager.GetString("ModalLoginInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string ModalNotificationInfoHeader {
            get {
                return ResourceManager.GetString("ModalNotificationInfoHeader", resourceCulture);
            }
        }
    }
}
