//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Views.Tariff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TariffVewsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TariffVewsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Views.Tariff.TariffVewsStrings", typeof(TariffVewsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковские карты.
        /// </summary>
        public static string ContentPayCard {
            get {
                return ResourceManager.GetString("ContentPayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li style=&quot;color: black&quot;&gt;Карты Visa, MasterCard - комиссия &lt;strong&gt;3.5%&lt;/strong&gt;&lt;/li&gt;
        ///                            &lt;li style=&quot;color: black&quot;&gt;Карта American Express  - комиссия &lt;strong&gt;4.5%&lt;/strong&gt; &lt;/li&gt;.
        /// </summary>
        public static string ContentPayCardDescription {
            get {
                return ResourceManager.GetString("ContentPayCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронные деньги.
        /// </summary>
        public static string ContentPayEMoney {
            get {
                return ResourceManager.GetString("ContentPayEMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминалы оплаты.
        /// </summary>
        public static string ContentPayTerminal {
            get {
                return ResourceManager.GetString("ContentPayTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li style=&quot;color: black&quot;&gt;Cумма до 20 тыс. тг &amp;ndash; комиссия &lt;strong&gt;1.5%&lt;/strong&gt;&lt;/li&gt;
        ///                            &lt;li style=&quot;color: black&quot;&gt;Сумма более 20 тыс. тг &amp;ndash; комиссия &lt;strong&gt;1%&lt;/strong&gt;&lt;/li&gt;.
        /// </summary>
        public static string ContentPayTerminalDescription {
            get {
                return ResourceManager.GetString("ContentPayTerminalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS уведомления.
        /// </summary>
        public static string ContentSmsNotification {
            get {
                return ResourceManager.GetString("ContentSmsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li style=&quot;color: black&quot;&gt;Стоимость 1 уведомления &amp;ndash; &lt;strong&gt;20 тг&lt;/strong&gt;&lt;/li&gt;
        ///                            &lt;li style=&quot;color: black&quot;&gt;Подписка на уведомления сроком на полгода &amp;ndash; &lt;strong&gt;500 тг&lt;/strong&gt;&lt;/li&gt;.
        /// </summary>
        public static string ContentSmsNotificationDescription {
            get {
                return ResourceManager.GetString("ContentSmsNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиссии за использование сервиса.
        /// </summary>
        public static string TitleTariff {
            get {
                return ResourceManager.GetString("TitleTariff", resourceCulture);
            }
        }
    }
}
