//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.PCP.Web.Resources.Models.Cabinet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CabinetViewModelsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CabinetViewModelsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DT.PCP.Web.Resources.Models.Cabinet.CabinetViewModelsStrings", typeof(CabinetViewModelsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование ЮЛ.
        /// </summary>
        public static string ArtificialPerson {
            get {
                return ResourceManager.GetString("ArtificialPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет ТС.
        /// </summary>
        public static string CarColor {
            get {
                return ResourceManager.GetString("CarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка ТС.
        /// </summary>
        public static string CarMark {
            get {
                return ResourceManager.GetString("CarMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МодельТС.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГРНЗ.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРТС.
        /// </summary>
        public static string CarPassportNumber {
            get {
                return ResourceManager.GetString("CarPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес регистрации.
        /// </summary>
        public static string CarRegistrationAddress {
            get {
                return ResourceManager.GetString("CarRegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год выпуска ТС.
        /// </summary>
        public static string CarYear {
            get {
                return ResourceManager.GetString("CarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма штрафа.
        /// </summary>
        public static string ColumnCost {
            get {
                return ResourceManager.GetString("ColumnCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата нарушения.
        /// </summary>
        public static string ColumnFixationTime {
            get {
                return ResourceManager.GetString("ColumnFixationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО нарушителя.
        /// </summary>
        public static string ColumnFullName {
            get {
                return ResourceManager.GetString("ColumnFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № предписания.
        /// </summary>
        public static string ColumnOrderNumber {
            get {
                return ResourceManager.GetString("ColumnOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес нарушения.
        /// </summary>
        public static string ColumnPostAddress {
            get {
                return ResourceManager.GetString("ColumnPostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип нарушения.
        /// </summary>
        public static string ColumnViolationType {
            get {
                return ResourceManager.GetString("ColumnViolationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения.
        /// </summary>
        public static string ConfirmationNotificationCode {
            get {
                return ResourceManager.GetString("ConfirmationNotificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО владельца.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон .
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены недопустимые символы.
        /// </summary>
        public static string ValdiationWrongData {
            get {
                return ResourceManager.GetString("ValdiationWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат почты.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат года.
        /// </summary>
        public static string ValidationErrorYear {
            get {
                return ResourceManager.GetString("ValidationErrorYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверынй код подтверждения.
        /// </summary>
        public static string ValidationNotificationCode {
            get {
                return ResourceManager.GetString("ValidationNotificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат номера.
        /// </summary>
        public static string ValidationPhoneNumber {
            get {
                return ResourceManager.GetString("ValidationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это обязательное поле.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
    }
}
